services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails:cached
      - bundle-cache:/usr/local/bundle
    environment:
      RAILS_ENV: development
      BINDING: "0.0.0.0"
      DB_HOST: postgres
    working_dir: /rails
    command:
      - bash
      - -c
      - |
        bundle install
        ./bin/rails db:prepare
        exec ./bin/rails server
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      dev.orbstack.http-port: "3000"

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bundle-cache:
  postgres-data:
