FROM ruby:4.0.1-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential git libpq-dev libyaml-dev pkg-config \
    curl libvips postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails
